default: &default
  adapter: postgresql
  # user: your_postgresql_username
  # password: your_postgresql_password
  # host: localhost or ip of your host 
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: your_app_name

test:
  <<: *default
  database: your_app_name

production:
  <<: *default
  database: your_app_name
  username: your_postgresql_username
  password: <%= ENV["DATABASE_PASSWORD"] %>